name: Bug Report
description: Report a problem with Save2MD
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill in the details below.

  - type: input
    id: version
    attributes:
      label: Extension version
      description: Found on chrome://extensions/
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Chrome
        - Chromium
        - Brave
        - Edge
        - Vivaldi
        - Other
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser version
      placeholder: "122.0.6261.69"
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: URL where the issue occurred
      description: If the issue is site-specific, include the URL (public pages only)
      placeholder: "https://example.com/article"
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
    validations:
      required: false
